
export const boardListStyles: Record<string, React.CSSProperties> = {
  container: {
    minHeight: '100vh',
    background: '#f9fafb',
    display: 'flex',
    flexDirection: 'column',
    paddingTop: 56,
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 16px',
    background: '#fff',
    borderBottom: '1px solid #e5e7eb',
    boxShadow: '0 1px 2px rgba(0,0,0,0.04)',
  },
  title: { margin: 0, fontSize: 16, fontWeight: 600, color: '#1e293b' },
  userRow: { display: 'flex', alignItems: 'center', gap: 12 },
  email: { fontSize: 13, color: '#6b7280' },
  main: { flex: 1, padding: '24px 24px 24px', maxWidth: 1200, margin: '0 auto', width: '100%' },
  tabBar: { display: 'flex', gap: 4, marginBottom: 16, paddingRight: 245 },
  tabBtn: {
    padding: '7px 16px',
    fontSize: 13,
    fontWeight: 500,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    background: '#fff',
    color: '#6b7280',
    cursor: 'pointer',
  },
  tabBtnActive: { background: '#374151', color: '#fff', borderColor: '#374151' },
  toolbar: { marginBottom: 20, paddingRight: 245, display: 'flex', flexDirection: 'column', gap: 10 },
  toolbarTop: { display: 'flex', alignItems: 'center', gap: 8 },
  searchInput: {
    flex: 1,
    padding: '9px 14px',
    fontSize: 14,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    background: '#fff',
    color: '#374151',
    outline: 'none',
  },
  sortGroup: { display: 'flex', gap: 4, background: '#f3f4f6', borderRadius: 8, padding: 3 },
  sortBtn: {
    padding: '5px 12px',
    fontSize: 13,
    fontWeight: 500,
    border: 'none',
    borderRadius: 6,
    background: 'transparent',
    color: '#6b7280',
    cursor: 'pointer',
  },
  sortBtnActive: { background: '#fff', color: '#374151', boxShadow: '0 1px 3px rgba(0,0,0,0.1)' },
  joinRow: { display: 'flex', gap: 8 },
  joinInput: {
    flex: 1,
    padding: '10px 14px',
    fontSize: 14,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    background: '#fff',
    color: '#374151',
  },
  joinBtn: {
    padding: '10px 20px',
    fontSize: 13,
    fontWeight: 500,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    background: '#fff',
    color: '#374151',
    cursor: 'pointer',
  },
  joinError: { margin: 0, fontSize: 13, color: '#b91c1c' },
  createBtn: {
    padding: '12px 24px',
    fontSize: 15,
    fontWeight: 500,
    border: 'none',
    borderRadius: 8,
    background: '#374151',
    color: '#fff',
    cursor: 'pointer',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
    gridAutoRows: 'auto',
    columnGap: 16,
    rowGap: 20,
    alignItems: 'stretch',
    listStyle: 'none',
    margin: 0,
    padding: 0,
    paddingRight: 245,
  },
  gridItem: { minWidth: 0, display: 'flex' },
  skeletonCard: { aspectRatio: '4/3', borderRadius: 12, background: '#e5e7eb', minHeight: 140 },
  emptyWrap: { textAlign: 'center', padding: '48px 24px' },
  empty: { color: '#6b7280', fontSize: 16, marginBottom: 16 },
  emptyCreateBtn: {
    padding: '12px 24px',
    fontSize: 15,
    fontWeight: 500,
    border: 'none',
    borderRadius: 8,
    background: '#374151',
    color: '#fff',
    cursor: 'pointer',
  },
  boardCard: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    background: '#fff',
    border: '1px solid #e5e7eb',
    borderRadius: 12,
    boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
    cursor: 'pointer',
    overflow: 'hidden',
  },
  boardThumb: { width: '100%', height: 130, flexShrink: 0, background: '#f3f4f6', overflow: 'hidden' },
  boardThumbImg: { width: '100%', height: '100%', objectFit: 'cover' as const, display: 'block' },
  boardThumbPlaceholder: {
    width: '100%',
    height: '100%',
    background: 'linear-gradient(135deg, #e5e7eb 0%, #f3f4f6 100%)',
  },
  boardCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
    minWidth: 0,
    padding: '10px 12px 0',
  },
  boardCardMain: { flex: 1, minWidth: 0 },
  boardTitle: {
    fontWeight: 500,
    color: '#374151',
    fontSize: 15,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    display: 'block',
  },
  renameInput: {
    width: '100%',
    padding: '4px 8px',
    fontSize: 15,
    border: '1px solid #e5e7eb',
    borderRadius: 6,
    outline: 'none',
    boxSizing: 'border-box',
  },
  boardMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
    marginBottom: 10,
    padding: '0 12px',
    flexWrap: 'wrap' as const,
  },
  boardDate: { fontSize: 12, color: '#9ca3af' },
  objectCount: { fontSize: 11, color: '#9ca3af' },
  publicBadge: { fontSize: 11, color: '#059669', background: '#ecfdf5', padding: '1px 6px', borderRadius: 4 },
  explorerBadge: { fontSize: 11, color: '#b45309', background: '#fef3c7', padding: '1px 6px', borderRadius: 4 },
  createMenu: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: 4,
    minWidth: 180,
    padding: 4,
    background: '#fff',
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
    zIndex: 20,
  },
  createMenuItem: {
    display: 'block',
    width: '100%',
    padding: '8px 12px',
    textAlign: 'left' as const,
    fontSize: 14,
    border: 'none',
    borderRadius: 6,
    background: 'transparent',
    color: '#374151',
    cursor: 'pointer',
  },
  actionsWrap: { position: 'relative', flexShrink: 0 },
  kebabBtn: {
    width: 32,
    height: 32,
    padding: 0,
    border: 'none',
    borderRadius: 6,
    background: 'transparent',
    color: '#6b7280',
    fontSize: 18,
    lineHeight: 1,
    cursor: 'pointer',
  },
  menuItem: {
    display: 'block',
    width: '100%',
    padding: '8px 12px',
    textAlign: 'left',
    fontSize: 13,
    border: 'none',
    borderRadius: 6,
    background: 'transparent',
    color: '#374151',
    cursor: 'pointer',
  },
  menuItemDanger: { color: '#b91c1c' },
  modalBackdrop: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },
  modal: {
    background: '#fff',
    borderRadius: 8,
    padding: 24,
    maxWidth: 360,
    boxShadow: '0 4px 24px rgba(0,0,0,0.15)',
  },
  modalTitle: { margin: 0, fontSize: 18, fontWeight: 600, color: '#374151' },
  modalBody: { margin: '12px 0 20px', fontSize: 14, color: '#6b7280' },
  modalActions: { display: 'flex', justifyContent: 'flex-end', gap: 8 },
  cancelBtn: {
    padding: '8px 16px',
    fontSize: 13,
    fontWeight: 500,
    border: '1px solid #e5e7eb',
    borderRadius: 6,
    background: '#fff',
    color: '#374151',
    cursor: 'pointer',
  },
  pagination: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    marginTop: 24,
    paddingRight: 245,
  },
  pageBtn: {
    padding: '7px 16px',
    fontSize: 13,
    fontWeight: 500,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    background: '#fff',
    color: '#374151',
    cursor: 'pointer',
  },
  pageBtnDisabled: { color: '#d1d5db', cursor: 'not-allowed' },
  pageInfo: { fontSize: 13, color: '#374151', fontWeight: 500 },
  pageTotal: { fontWeight: 400, color: '#9ca3af' },
  deleteBtn: {
    padding: '8px 16px',
    fontSize: 13,
    fontWeight: 500,
    border: 'none',
    borderRadius: 6,
    background: '#b91c1c',
    color: '#fff',
    cursor: 'pointer',
  },
}
